### ISSUE TITLE
support environment id passing to Qase

### ISSUE THREAD

**Issue by sharovatov** [qase-tms/qase-php#4]
both codeception and phpunit don't support passing environment ID from the config or params to Qase, please add this functionality to both.

reference implementation (in JS) can be found here: https://github.com/qase-tms/qase-javascript/blob/master/qase-cypress/src/index.ts

**Comment by in4s** [comment]
Hi! Should this param be required?

**Comment by in4s** [comment]
I guess not, as far as here https://github.com/qase-tms/qase-javascript/tree/master/qase-cypress this param is not marked as required.

**Comment by sharovatov** [comment]
thanks @in4s 

https://github.com/qase-tms/qase-phpunit/pull/25 and https://github.com/qase-tms/qase-codeception/pull/3 PRs close this issue
